### ISSUE TITLE
LANG_007 Testing mode

### ISSUE THREAD

**Issue by sw20-tugraz** [sw20-tug/ASD-Afternoon-1#9]
As a user I want to test myself with random vocabulary and finish the test once I know all of them.

**Acceptance criteria:**
- Pick random vocabulary add them to test
- Repeat not known vocabulary (at least X times which can be configured)
- View results of test (accuracy, list of worst vocabularies, ...)

**Comment by M-Schiller** [comment]
Split up into #62, #63, #64

**Comment by M-Schiller** [comment]
Done - as all related issues are done.
